let a=100;
let b=20;
document.write(a+b," ");
document.write(a-b," ");
document.write(a*b," ");
document.write(a/b," ");
document.write(a%b," ");
document.write(a++," ");
document.write(++a," ");
document.write(--b," ");
document.write(b--," ")